name: Coverage Report

on:
  push:
    branches:
      - main
      - group31-fall24
  pull_request:
    branches:
      - main
      - group31-fall24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend setup
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest pytest-cov flask firebase-admin flask-cors
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Build init file
        run: |
          cd backend
          cd src
          touch __init__.py
          echo "import pyrebase" >> __init__.py
          echo "config = {" >> __init__.py
          echo "  'apiKey': \"${{ secrets.API_KEY }}\", " >> __init__.py
          echo "  'authDomain': \"${{ secrets.AUTH_DOMAIN }}\", " >> __init__.py
          echo "  'databaseURL': \"${{ secrets.DATABASE_URL }}\", " >> __init__.py
          echo "  'projectId': \"${{ secrets.PROJECT_ID }}\", " >> __init__.py
          echo "  'storageBucket': \"${{ secrets.STORAGE_BUCKET }}\", " >> __init__.py
          echo "  'messagingSenderId': \"${{ secrets.MESSAGING_ID }}\", " >> __init__.py
          echo "  'appId': \"${{ secrets.APP_ID }}\" " >> __init__.py
          echo "} " >> __init__.py
          echo "firebase = pyrebase.initialize_app(config) " >> __init__.py

      - name: Run backend tests with coverage
        run: |
          cd backend
          python -m pytest --cov=src --cov-report=term-missing
          python -m coverage xml
          python -m coverage html

      # # Frontend setup
      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20.17.0'

      # - name: Install frontend dependencies
      #   run: |
      #     cd frontend
      #     npm install --force

      # - name: Run frontend tests with coverage
      #   run: |
      #     cd frontend
      #     npm test -- --coverage --coverageReporters=lcov  # Ensure correct report generation

      # Upload coverage reports to Codecov
      - name: Upload backend coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./backend/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      # - name: Upload frontend coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: ./frontend/coverage/lcov.info  # Update based on actual path
      #     flags: unittests
      #     name: codecov-frontend
      #     fail_ci_if_error: true
      #     verbose: true

      # Archive code coverage results
      - name: Archive backend coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            backend/coverage.xml
            backend/htmlcov

      # - name: Archive frontend coverage results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: frontend-code-coverage-report
      #     path: frontend/coverage
