name: Documentation Generator

on:
  push:
    branches:
      - main
      - group31-fall24

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write  # This is important for pushing to the repository

        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic GITHUB_TOKEN
                fetch-depth: 0  # Fetch all history for all branches and tags
                
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install sphinx
                    if [ -f backend/test/requirements.txt ]; then pip install -r backend/test/requirements.txt; fi

            - name: Generate Documentation
              run: |
                chmod u+x backend
                chmod u+x backend/Documentation
                sphinx-build -b html backend backend/Documentation

            - name: Commit and Push Changes
              run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add -A
                git commit -m "Auto-generate documentation" || echo "No changes to commit"
                git push

            # Alternative push method if the above doesn't work
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}